import type { BootstrapSnapshot, TaskDetailSnapshot, VocabularySnapshot } from "../src/model";

const epoch = "4f4b5d2a88d31001";
const now = 1788086880;

export const vocabularyFixture: VocabularySnapshot = {
  epoch,
  task_status: [
    { value: "in-progress", label: "进行中", glyph: "▶" },
    { value: "submitted", label: "已提交", glyph: "◆" },
    { value: "blocked", label: "阻塞", glyph: "!" },
    { value: "accepted", label: "已验收", glyph: "✓" },
  ],
  event_kind: [
    { value: "created", label: "建立" },
    { value: "assigned", label: "派工" },
    { value: "progress", label: "进展" },
    { value: "evidence", label: "证据" },
    { value: "submitted", label: "提交" },
  ],
  member_state: [
    { value: "working", label: "WORK", glyph: "▶" },
    { value: "idle", label: "IDLE", glyph: "○" },
    { value: "stuck", label: "STUCK", glyph: "!" },
    { value: "dead", label: "DEAD", glyph: "×" },
  ],
  timeline_category: [
    { value: "all", label: "全部" },
    { value: "human", label: "human 往来" },
    { value: "ai", label: "成员协作" },
    { value: "task", label: "任务事件" },
    { value: "control", label: "控制事件" },
  ],
  timeline_outcome: [
    { value: "delivered", label: "已投递", glyph: "✓", dim: false },
    { value: "shown", label: "已显示", glyph: "·", dim: false },
    { value: "rejected", label: "已拒收", glyph: "×", dim: true },
  ],
  event_detail_fields: [
    { key: "summary", label: "摘要" },
    { key: "reference", label: "引用" },
    { key: "reviewer", label: "评审者" },
  ],
};

const timelineEntries = [
  {
    seq: 37,
    key: "msg-37",
    at: now - 420,
    ts: "2026-08-30 18:41:08",
    sender: "fable",
    to: "human",
    text: "WEB-006 的浏览器消息边界可以开始实现了吗？",
    outcome: "delivered",
    reason: "",
    task_id: "T-016",
    attachment_count: 0,
    category: "human" as const,
    has_body: true,
    kind: "ask" as const,
    reply_to: null,
    attachment_ids: [],
  },
  {
    seq: 38,
    key: "task-38",
    at: now - 330,
    ts: "2026-08-30T18:42:31Z",
    sender: "work",
    to: "team",
    text: "T-016 · 进展：完成认证消息与附件边界",
    outcome: "shown",
    reason: "",
    task_id: "T-016",
    attachment_count: 0,
    category: "task" as const,
    has_body: false,
    kind: null,
    reply_to: null,
    attachment_ids: [],
  },
  {
    seq: 39,
    key: "msg-39",
    at: now - 270,
    ts: "2026-08-30 18:43:02",
    sender: "human",
    to: "team",
    text: "界面需要保持证据链清晰，也要让成员状态一眼可读。",
    outcome: "delivered",
    reason: "",
    task_id: null,
    attachment_count: 0,
    category: "human" as const,
    has_body: true,
    kind: null,
    reply_to: null,
    attachment_ids: [],
  },
  {
    seq: 40,
    key: "msg-40",
    at: now - 180,
    ts: "2026-08-30 18:44:50",
    sender: "opus",
    to: "sol",
    text: "时间线按原始 ts 的分钟片段分组；成员相对时间只从 silent_for 与 snapshot_at 推导。",
    outcome: "delivered",
    reason: "",
    task_id: "T-016",
    attachment_count: 0,
    category: "ai" as const,
    has_body: true,
    kind: null,
    reply_to: null,
    attachment_ids: [],
  },
  {
    seq: 41,
    key: "control-41",
    at: now - 90,
    ts: "2026-08-30 18:46:12",
    sender: "control",
    to: "sol",
    text: "成员窗口不可用，控制动作未执行",
    outcome: "rejected",
    reason: "tmux session missing",
    task_id: null,
    attachment_count: 0,
    category: "control" as const,
    has_body: false,
    kind: null,
    reply_to: null,
    attachment_ids: [],
  },
];

export const bootstrapFixture: BootstrapSnapshot = {
  epoch,
  revisions: { workspace: 1, team: 2, roster: 3, work: 14, timeline: 41, member: 32, health: 2 },
  session: {
    actor: "human",
    write_token: "fixture-write-token",
    epoch,
    epoch_started_at: now - 7200,
    server_time_at: now,
    revisions: { workspace: 1, team: 2, roster: 3, work: 14, timeline: 41, member: 32, health: 2 },
    capabilities: { stream: false, mirror: false, compose: true, control: false },
  },
  workspace: {
    epoch,
    revision: 1,
    registered: true,
    slug: "proj-multi-agent",
    project_root: "/Users/jzhang/Downloads/proj_multi_agent",
  },
  team: {
    epoch,
    revision: 2,
    bound: true,
    id: "fable-core",
    name: "Fable Core",
    description: "构建可回看、可验证的多智能体协作工作台。",
    leader: "fable",
    members: [
      { id: "fable", role: "leader", model: "Codex", effort: "high", speed: "standard", responsibility: "目标拆解、验收与协作调度" },
      { id: "sol", role: "member", model: "Sol", effort: "high", speed: "standard", responsibility: "独立实现、交叉验证与高难任务支持" },
      { id: "opus", role: "member", model: "Opus", effort: "high", speed: "standard", responsibility: "复杂问题分析、方案评审与风险检查" },
      { id: "grok", role: "member", model: "Grok", effort: "high", speed: "fast", responsibility: "实时协议与后端系统实现" },
    ],
  },
  work: {
    epoch,
    revision: 14,
    summary: {
      leader: "fable",
      active: 3,
      waiting: 1,
      blocked: 1,
      total: 6,
      by_status: { "in-progress": 2, submitted: 1, blocked: 1, accepted: 2 },
    },
    tasks: [
      { id: "T-016", title: "WEB-006 消息、ask/reply 与浏览器附件", status: "in-progress", assignee: "sol", reviewer: "opus", parent_id: null, completed: false, created_at: now - 5400, updated_at: now - 60, created_ts: "2026-08-30T09:16:00Z", updated_ts: "2026-08-30T10:47:00Z" },
      { id: "T-013", title: "WEB-004 versioned 实时事件流", status: "in-progress", assignee: "grok", reviewer: "opus", parent_id: null, completed: false, created_at: now - 7600, updated_at: now - 300, created_ts: "2026-08-30T08:45:00Z", updated_ts: "2026-08-30T10:43:00Z" },
      { id: "T-012", title: "Web snapshot 性能复核", status: "submitted", assignee: "sonnet", reviewer: "fable", parent_id: null, completed: false, created_at: now - 12000, updated_at: now - 800, created_ts: "2026-08-30T07:02:00Z", updated_ts: "2026-08-30T10:35:00Z" },
      { id: "T-011", title: "前端工程脚手架", status: "accepted", assignee: "luna", reviewer: "fable", parent_id: null, completed: true, created_at: now - 18000, updated_at: now - 1200, created_ts: "2026-08-30T05:25:00Z", updated_ts: "2026-08-30T10:28:00Z" },
      { id: "T-010", title: "协议一致性检查", status: "blocked", assignee: "composer", reviewer: "opus", parent_id: null, completed: false, created_at: now - 21000, updated_at: now - 1800, created_ts: "2026-08-30T04:35:00Z", updated_ts: "2026-08-30T10:18:00Z" },
      { id: "T-009", title: "Web 后端 snapshot 收口", status: "accepted", assignee: "sol", reviewer: "opus", parent_id: null, completed: true, created_at: now - 26000, updated_at: now - 3600, created_ts: "2026-08-30T03:12:00Z", updated_ts: "2026-08-30T09:48:00Z" },
    ],
    selected_default: "T-016",
  },
  members: {
    epoch,
    revision: 32,
    snapshot_at: now,
    members: [
      { name: "fable", state: "working", queued: 0, silent_for: 4, alive: true, source: "roster" },
      { name: "sol", state: "working", queued: 2, silent_for: 12, alive: true, source: "roster" },
      { name: "opus", state: "idle", queued: 0, silent_for: 185, alive: true, source: "roster" },
      { name: "grok", state: "stuck", queued: 1, silent_for: 392, alive: true, source: "roster" },
    ],
  },
  health: {
    epoch,
    revision: 2,
    degraded: true,
    faults: [{ key: "member-session:composer", kind: "member-session", target: "composer", detail: "成员会话暂不可达；其余只读视图保持可用" }],
  },
  timeline: {
    epoch,
    revision: 41,
    entries: timelineEntries,
    category_counts: { all: 41, human: 5, ai: 25, task: 9, control: 2 },
    head_seq: 41,
    oldest_seq: 37,
    has_more: true,
  },
};

export const taskDetailFixture: TaskDetailSnapshot = {
  epoch,
  revision: 14,
  task: {
    id: "T-016",
    title: "WEB-006 消息、ask/reply 与浏览器附件",
    description: "基于一致 snapshot 构建完整只读工作台：任务、成员、时间线、证据和导航在一个桌面界面中形成闭环。",
    leader: "fable",
    parent_id: null,
    status: "in-progress",
    assignee: "sol",
    reviewer: "opus",
    accepted_by: null,
    completed: false,
    latest: "Preact 信息架构已落地，正在补齐轻量组件测试与视觉验证。",
    created_at: now - 5400,
    updated_at: now - 60,
    created_ts: "2026-08-30T09:16:00Z",
    updated_ts: "2026-08-30T10:47:00Z",
    evidence: [
      "web/tests/unit/app.test.tsx · snapshot 视图与导航",
      "tests/baseline/web-006-compose-1440x1000.png · 实际截图",
      "docs/web/api-protocol.md §4.8/§4.9/§4.10",
    ],
  },
  children: [{ id: "T-015", title: "交互动作与消息输入", status: "backlog" }],
  events: [
    { seq: 1, id: "event-1", kind: "created", actor: "fable", at: now - 5400, ts: "2026-08-30T09:16:00Z", details: { summary: "建立 WEB-006 任务" } },
    { seq: 2, id: "event-2", kind: "assigned", actor: "fable", at: now - 5100, ts: "2026-08-30T09:21:00Z", details: { summary: "指派 sol", reviewer: "opus" } },
    { seq: 3, id: "event-3", kind: "progress", actor: "sol", at: now - 2400, ts: "2026-08-30T10:06:00Z", details: { summary: "完成框架定案与三栏信息架构" } },
    { seq: 4, id: "event-4", kind: "evidence", actor: "sol", at: now - 600, ts: "2026-08-30T10:36:00Z", details: { reference: "web/src/app.tsx" } },
  ],
  communications: [
    { timeline_seq: 37, sender: "fable", to: "sol", text: "先完成 snapshot 驱动的只读视图。", attachment_count: 0, at: now - 420, ts: "2026-08-30 18:41:08" },
    { timeline_seq: 40, sender: "opus", to: "sol", text: "颜色、分钟分组和相对时间严格按协议实现。", attachment_count: 0, at: now - 180, ts: "2026-08-30 18:44:50" },
  ],
};
